# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://django-danceschool.org/
title: Django Dance School
email: info@django-danceschool.org
author: Lee Tucker
description: > # "Write an awesome description for your new site here. 
  The Django Dance School Project is a django CMS based project for running partnered dance schools of
  all types.  It includes features for easy management of registration, instructors, discounts, vouchers,
  prerequisites, and financial management, as well as easy integration with both Paypal and Stripe payment
  processors.  It is designed to be flexible, modular, and easy to set up for dance schools and studios
  of all types. 
copyright: 'Copyright &copy; 2017 Lee Tucker.'
credits: 'Credits: Landing Page theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

collections:
  highlights:
    title: Highlights


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Github
    url: https://github.com/django-danceschool/django-danceschool
    fa_icon_class: github
  - title: Read the Docs
    url: http://django-danceschool.readthedocs.io/en/latest/
    fa_icon_class: book
